import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
import "@/app/globals.css";

import { cn } from "@/lib/utils";
import { Navbar } from "@/components/shared/navbar";
import { Footer } from "@/components/shared/footer";
import { Toaster } from "sonner";
import { GetMe } from "@/components/service/getme";

const publicSans = Public_Sans({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user = null;
  try {
    user = await GetMe();
  } catch (error) {
    user = null;
  }

   return (
    // এখানে কোনো <html> বা <body> থাকবে না, শুধু আপনার দরকারী ডিভ বা ফ্র্যাগমেন্ট থাকবে
   
    <div className="w-full">
         <Navbar user={user}></Navbar>
      {children}
      <Footer></Footer>
    </div>
  )
}