import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
import "@/app/globals.css";

import { cn } from "@/lib/utils";
import { Navbar } from "@/components/shared/navbar";
import { Footer } from "@/components/shared/footer";
import { Toaster } from "sonner";
import { GetMe } from "@/components/service/getme";

const publicSans = Public_Sans({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FixItNow",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user = null;
  try {
    user = await GetMe();
  } catch (error) {
    user = null;
  }

  return (


    <div className="flex min-h-screen flex-col w-full z-10">
      <Navbar user={user} />

      <main className="flex-1 w-full pb-0 overflow-hidden">
        {children}
      </main>


      <Footer />
    </div>
  )
}